# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a549cf7f956314572c080f7f21c1e1d39b01c730c4823023e09a867af48276d5a447bcdefd7b3c046c7d9695276e3847a1b947751d9e12fb4e28d15b9452947

test:
  secret_key_base: 8be5b3e4a4fa96c077983b8f767a07c3ce93ac9e0436444b1b81ccf3adc581fe120cce065210c63768e84f4c4bc4cf70fb6283a4ae46466b38d5f13bfcc98aa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
